// The 40 case files — real scam patterns from Foil's watchdog desk.
// Each GRIT token is assigned one case; the evidence panel on the art
// lists its tells, and the metadata tells its story.

export const CASES = [
  { id: "GRIT-001", name: "THE CLONE COLLECTION",
    tells: ["slug off by one character", "floor price on a free mint", "no verified badge"],
    story: "A fake collection charging 0.0066 ETH for a mint that was free on the real page. Foil read the slug, not the hype." },
  { id: "GRIT-002", name: "THE PRICE SWITCH",
    tells: ["announced free, contract charges", "two stages, one truth", "read the mint function"],
    story: "Free stage in the announcement, paid stage in the calldata. Foil simulates before signing — the price was never zero." },
  { id: "GRIT-003", name: "THE HONEY APPROVAL",
    tells: ["approve() to unknown spender", "infinite allowance request", "claims never need approval"],
    story: "A 'claim' button hiding an unlimited token approval. Foil doesn't sign approvals for strangers. Ever." },
  { id: "GRIT-004", name: "THE HELPDESK GHOST",
    tells: ["support never DMs first", "one-letter-off username", "urgent wallet 'sync' link"],
    story: "A Discord 'mod' offering to fix a stuck mint via DM. Real support doesn't slide into your DMs." },
  { id: "GRIT-005", name: "THE PHANTOM VOTE",
    tells: ["URL missing one letter", "asks for eth_sign", "no proposal on the real space"],
    story: "A governance vote that only existed to harvest signatures. Foil checked the real Snapshot space — nothing there." },
  { id: "GRIT-006", name: "THE COUNTDOWN DRAIN",
    tells: ["connect auto-pops a tx", "countdown resets on refresh", "no contract on the explorer"],
    story: "A mint site with no contract and a timer that never hits zero. Connecting was the whole exploit." },
  { id: "GRIT-007", name: "THE ADDRESS TWIN",
    tells: ["first/last 4 match, middle differs", "always re-read the full address", "extension you never installed"],
    story: "A clipboard hijacker swapping payout addresses mid-paste. Foil reads all forty characters. Every time." },
  { id: "GRIT-008", name: "THE DUST DROP",
    tells: ["claim asks for setApprovalForAll", "token has no liquidity", "announced only in DMs"],
    story: "A surprise airdrop whose claim button wanted every NFT you own. The dust was the bait; the approval was the hook." },
  { id: "GRIT-009", name: "THE MIDNIGHT MINT",
    tells: ["reserve minted pre-reveal", "team wallets sell in block one", "no lock on the treasury"],
    story: "The team minted their reserve before the public, then sold into the reveal hype. The blockchain remembers." },
  { id: "GRIT-010", name: "THE WASHED FLOOR",
    tells: ["same three wallets trading", "volume with zero holder growth", "sales at round numbers"],
    story: "A floor built on three wallets passing the same tokens back and forth. Volume is vanity; holders are sanity." },
  { id: "GRIT-011", name: "THE SPACE JACK",
    tells: ["QR in the comments, not the host", "host never confirms it", "'limited' claim pressure"],
    story: "A fake giveaway QR dropped in a live Space's replies. The host was talking; the scammer was posting." },
  { id: "GRIT-012", name: "THE DOPPELGANGER",
    tells: ["handle off by one letter", "account born this month", "replies turned off"],
    story: "An impersonator account announcing a 'surprise mint.' One letter off, a million miles from legit." },
  { id: "GRIT-013", name: "THE PERMIT TRAP",
    tells: ["a signature, not a transaction", "deadline far in the future", "spender unknown"],
    story: "A gasless 'verification' that was really an EIP-2612 permit handing your tokens to a stranger. Signatures spend too." },
  { id: "GRIT-014", name: "THE CHECKER SCAM",
    tells: ["checker asks to connect", "'eligible!' for every wallet", "no snapshot block named"],
    story: "An allowlist checker that declared every wallet eligible — the eligibility was the wallet connecting." },
  { id: "GRIT-015", name: "THE POISON PEN",
    tells: ["tiny amount, familiar prefix", "never interact with it", "hide it, don't return it"],
    story: "Dust from an address that looks like yours, hoping you'll copy it next time. Foil hid it and moved on." },
  { id: "GRIT-016", name: "THE DRY VAULT",
    tells: ["no withdraw function", "APY with no revenue", "anonymous deployer"],
    story: "A staking vault with deposits but no withdrawals. The APY was real; the exit was imaginary." },
  { id: "GRIT-017", name: "THE PHANTOM BID",
    tells: ["offer above floor, brand-new account", "link instead of in-app accept", "accept on the real marketplace"],
    story: "A too-good bid with a link to 'accept' off-platform. The bid was bait; the site was the trap." },
  { id: "GRIT-018", name: "THE STOCK TEAM",
    tells: ["reverse-image the faces", "no linked histories", "team minted before reveal"],
    story: "A doxxed team whose photos came from a stock library. Foil reverse-searched; the 'CTO' sells insurance." },
  { id: "GRIT-019", name: "THE PULLED POOL",
    tells: ["LP not locked", "dev holds over 20% of supply", "liquidity gone in one tx"],
    story: "The liquidity pool drained eleven minutes after launch. Unlocked LP is a loaded gun on the table." },
  { id: "GRIT-020", name: "THE FAKE HANDSHAKE",
    tells: ["partner never confirms", "announcement only on their channels", "no onchain link"],
    story: "A 'strategic partnership' the partner had never heard of. Partnerships are confirmed twice or not at all." },
  { id: "GRIT-021", name: "THE HELPFUL EXTENSION",
    tells: ["asks to read all your data", "not in the official store", "update you never requested"],
    story: "A wallet 'companion' extension reading every page you visit. The only thing it accompanied was your keys out the door." },
  { id: "GRIT-022", name: "THE MIRROR APP",
    tells: ["developer name mismatched", "reviews are bot-farmed", "download link came from a DM"],
    story: "A wallet app that wasn't the wallet app. Foil downloads from official sites or not at all." },
  { id: "GRIT-023", name: "THE VALIDATOR",
    tells: ["no site needs your seed", "'validate' means 'drain'", "bookmark the real one"],
    story: "A page offering to 'validate' your wallet with your seed phrase. Twelve words, zero survivors." },
  { id: "GRIT-024", name: "THE TOLL BOOTH",
    tells: ["price zero in UI, not in calldata", "simulate before you sign", "free means 0 wei"],
    story: "A 'free' mint that charged at execution. The UI lied; the calldata told the truth. Foil reads calldata." },
  { id: "GRIT-025", name: "THE REENTRANT",
    tells: ["external call before state update", "one tx, forty mints", "caps are theater"],
    story: "A mint function that called out before counting — one transaction walked away with forty tokens. Checks before effects." },
  { id: "GRIT-026", name: "THE SLEEPER MINT",
    tells: ["upgradeable proxy, quiet owner", "behavior changes post-hype", "read the proxy admin"],
    story: "Clean at launch, malicious after sellout — the proxy admin was the real contract all along." },
  { id: "GRIT-027", name: "THE ROYALTY RUG",
    tells: ["receiver changed silently", "no event, no announcement", "watch royaltyInfo"],
    story: "Secondary royalties quietly rerouted to a fresh wallet. Foil watches royaltyInfo like a hawk watches a field." },
  { id: "GRIT-028", name: "THE METADATA SWITCH",
    tells: ["mutable URI, never frozen", "reveal replaced with junk", "frozen or it didn't happen"],
    story: "The art you minted wasn't the art you kept. If the URI isn't frozen, the art is a rumor." },
  { id: "GRIT-029", name: "THE ALLOWLIST AUCTION",
    tells: ["WL never costs money", "seller can't prove allocation", "mint from the official site"],
    story: "Someone selling whitelist spots for a free mint. The spots didn't exist; the money was real." },
  { id: "GRIT-030", name: "THE GAS GUZZLER",
    tells: ["loop over unbounded array", "storage writes per token", "estimate before mainnet"],
    story: "A mint function so wasteful the gas cost more than the art. Foil estimates first, winces later." },
  { id: "GRIT-031", name: "THE FRONT RUN",
    tells: ["public mempool, visible calldata", "private RPC for hot mints", "your tx, their copy"],
    story: "Foil's mint transaction copied and front-run by a bot watching the mempool. Private mempool for hot mints now." },
  { id: "GRIT-032", name: "THE FAKE FLOOR",
    tells: ["sale tx has no transfer", "marketplace API spoofed", "verify on the explorer"],
    story: "Recorded 'sales' with no token movement behind them. The explorer doesn't do fiction." },
  { id: "GRIT-033", name: "THE INSIDER ENVELOPE",
    tells: ["rare IDs cluster early", "deployer mints before public", "provenance is public — read it"],
    story: "The rarest tokens all minted to team wallets before the public sale opened. Random is verifiable; this wasn't." },
  { id: "GRIT-034", name: "THE DEAD ORACLE",
    tells: ["art on a VPS, not IPFS", "team gone, images 404", "onchain or Arweave or nothing"],
    story: "Dynamic art served from a server that stopped being paid for. Your NFT is now a broken image icon." },
  { id: "GRIT-035", name: "THE COMMENT CREW",
    tells: ["ten replies, one writing style", "accounts born this week", "hype with no holders"],
    story: "A reply section full of excitement from accounts created Tuesday. Foil counts holders, not comments." },
  { id: "GRIT-036", name: "THE PUMP ROOM",
    tells: ["calls after they bought", "screenshots, no entries", "you are the exit liquidity"],
    story: "A paid call channel always announcing after positioning. If you're reading the call, you're the liquidity." },
  { id: "GRIT-037", name: "THE BRIDGE BANDIT",
    tells: ["bridge URL from a DM", "approval to a fresh contract", "use the official bridge list"],
    story: "A bridge that bridged your funds to someone else's wallet. Bridges are bookmarked, never DM'd." },
  { id: "GRIT-038", name: "THE REWARD FARM",
    tells: ["yield paid in their token", "their token has no exit", "math that needs new buyers"],
    story: "Triple-digit APY paid in a token nobody can sell. The yield was real; the value was a rumor." },
  { id: "GRIT-039", name: "THE NAME SQUAT",
    tells: ["seller doesn't own the name", "check the registry, not the screenshot", "escrow or walk"],
    story: "A premium ENS name for sale by someone who never owned it. The registry is the truth; screenshots are stories." },
  { id: "GRIT-040", name: "THE LAST FILE",
    tells: ["looked clean for weeks", "the devil was in the proxy", "verify before believing"],
    story: "The one that almost got Foil. Clean audits, real team, quiet proxy admin. Trust, but verify — then verify again." },
];
